#!/bin/bash
# Build cjxl + djxl as universal static executables for macOS.
# Called from Xcode's "Run Script" build phase.
# Uses the same libjxl source tree as jpegli but with a separate build dir.
# Builds libjpeg-turbo from third_party for JPEG codec support.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SRC_DIR="$SCRIPT_DIR/src"
BUILD_ROOT="$SCRIPT_DIR/build-tools"
OUTPUT_DIR="$BUILD_ROOT"
LIBJPEG_SRC="$SRC_DIR/third_party/libjpeg-turbo"

# Use Xcode's deployment target if available, otherwise default
MACOSX_DEPLOYMENT_TARGET="${MACOSX_DEPLOYMENT_TARGET:-10.13}"
export MACOSX_DEPLOYMENT_TARGET

ARCHS=(arm64 x86_64)

mkdir -p "$OUTPUT_DIR"

# Check if we need to rebuild
MARKER="$OUTPUT_DIR/.build_marker"
if [ -f "$MARKER" ] && [ -f "$OUTPUT_DIR/cjxl" ] && [ -f "$OUTPUT_DIR/djxl" ]; then
    MARKER_TIME=$(stat -f %m "$MARKER" 2>/dev/null || echo 0)
    CJXL_SRC_TIME=$(stat -f %m "$SRC_DIR/tools/cjxl_main.cc" 2>/dev/null || echo 1)
    DJXL_SRC_TIME=$(stat -f %m "$SRC_DIR/tools/djxl_main.cc" 2>/dev/null || echo 1)
    CMAKE_TIME=$(stat -f %m "$SRC_DIR/CMakeLists.txt" 2>/dev/null || echo 1)
    MAX_SRC_TIME=$((CJXL_SRC_TIME > DJXL_SRC_TIME ? CJXL_SRC_TIME : DJXL_SRC_TIME))
    MAX_SRC_TIME=$((MAX_SRC_TIME > CMAKE_TIME ? MAX_SRC_TIME : CMAKE_TIME))
    if [ "$MARKER_TIME" -ge "$MAX_SRC_TIME" ]; then
        echo "jxl-tools: already built (up to date)"
        exit 0
    fi
fi

# Remove stale jpeglib.h that may have been generated by jpegli build
# (it shadows the real jpeglib.h from libjpeg-turbo)
rm -f "$SRC_DIR/jpeglib.h"

build_libjpeg() {
    local ARCH=$1
    local DEPS_DIR="$BUILD_ROOT/deps-$ARCH"
    local JPEG_BUILD="$DEPS_DIR/libjpeg"

    if [ -f "$DEPS_DIR/install/lib/libjpeg.a" ]; then
        return
    fi

    echo "jxl-tools: building libjpeg-turbo for $ARCH..."
    mkdir -p "$JPEG_BUILD"
    cmake -S "$LIBJPEG_SRC" -B "$JPEG_BUILD" \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_OSX_ARCHITECTURES="$ARCH" \
        -DCMAKE_OSX_DEPLOYMENT_TARGET="$MACOSX_DEPLOYMENT_TARGET" \
        -DCMAKE_C_FLAGS="-fPIC" \
        -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
        -DBUILD_SHARED_LIBS=OFF \
        -DENABLE_SHARED=OFF \
        -DENABLE_STATIC=ON \
        -DWITH_TURBOJPEG=OFF \
        -DCMAKE_INSTALL_PREFIX="$DEPS_DIR/install" \
        -G Ninja 2>&1 | tail -3
    cmake --build "$JPEG_BUILD" --config Release -- -j"$(sysctl -n hw.ncpu)" 2>&1 | tail -3
    cmake --install "$JPEG_BUILD" --config Release 2>&1 | tail -3
}

build_arch() {
    local ARCH=$1
    local BUILD_DIR="$BUILD_ROOT/$ARCH"
    local DEPS_DIR="$BUILD_ROOT/deps-$ARCH"

    # Build libjpeg-turbo first
    build_libjpeg "$ARCH"

    echo "jxl-tools: building for $ARCH..."
    mkdir -p "$BUILD_DIR"

    cmake -S "$SRC_DIR" -B "$BUILD_DIR" \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_OSX_ARCHITECTURES="$ARCH" \
        -DCMAKE_OSX_DEPLOYMENT_TARGET="$MACOSX_DEPLOYMENT_TARGET" \
        -DCMAKE_C_FLAGS="-fPIC" \
        -DCMAKE_CXX_FLAGS="-fPIC" \
        -DJPEGXL_ENABLE_TOOLS=ON \
        -DJPEGXL_ENABLE_JPEGLI=OFF \
        -DJPEGXL_STATIC=ON \
        -DBUILD_SHARED_LIBS=OFF \
        -DJPEGXL_BUNDLE_LIBPNG=ON \
        -DJPEGXL_ENABLE_OPENEXR=OFF \
        -DJPEGXL_ENABLE_SKCMS=OFF \
        -DJPEGXL_ENABLE_SJPEG=OFF \
        -DJPEGXL_ENABLE_BENCHMARK=OFF \
        -DJPEGXL_ENABLE_EXAMPLES=OFF \
        -DJPEGXL_ENABLE_MANPAGES=OFF \
        -DJPEGXL_ENABLE_DOXYGEN=OFF \
        -DBUILD_TESTING=OFF \
        -DCMAKE_DISABLE_FIND_PACKAGE_GIF=ON \
        -DCMAKE_PREFIX_PATH="$DEPS_DIR/install" \
        -G Ninja \
        2>&1 | tail -5

    cmake --build "$BUILD_DIR" --target cjxl djxl --config Release -- -j"$(sysctl -n hw.ncpu)" 2>&1 | tail -5
}

for ARCH in "${ARCHS[@]}"; do
    build_arch "$ARCH"
done

echo "jxl-tools: creating output binaries..."

for TOOL in cjxl djxl; do
    INPUTS=()
    for ARCH in "${ARCHS[@]}"; do
        TOOL_PATH="$BUILD_ROOT/$ARCH/tools/$TOOL"
        if [ ! -f "$TOOL_PATH" ]; then
            echo "ERROR: Could not find $TOOL for $ARCH at $TOOL_PATH"
            exit 1
        fi
        INPUTS+=("$TOOL_PATH")
    done
    if [ ${#INPUTS[@]} -eq 1 ]; then
        cp "${INPUTS[0]}" "$OUTPUT_DIR/$TOOL"
    else
        lipo -create "${INPUTS[@]}" -output "$OUTPUT_DIR/$TOOL"
    fi
    echo "  Created: $OUTPUT_DIR/$TOOL"
done

touch "$MARKER"
echo "jxl-tools: build complete."
