
VERSION=0.6.3

src/optipng.c:
	curl -L http://downloads.sourceforge.net/project/optipng/OptiPNG/optipng-$(VERSION)/optipng-$(VERSION).tar.gz | tar vxz --strip-components=1 optipng-$(VERSION)/src optipng-$(VERSION)/lib/pngxtern
	
	
clean:

install: