build: all

all: repng.cc

repng.cc:
	curl -L https://github.com/amadvance/advancecomp/releases/download/v2.6/advancecomp-2.6.tar.gz | tar xz --strip-components=1

clean:

install:

.PHONY: build all install clean
