build: all

all: repng.cc

repng.cc:
	curl -L http://sourceforge.net/projects/advancemame/files/advancecomp/1.15/advancecomp-1.15.tar.gz/download | tar xz --strip-components=1

clean:

install:

.PHONY: build all install clean
